# https://rubocop.readthedocs.io/en/stable/
require: rubocop-performance

# Preferences
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
