# Name of your application. Used to uniquely configure containers.
service: blog

# Name of the container image.
image: tjustino/blog

# Deploy to these servers.
servers:
  web:
    - 51.38.176.164

# Enable SSL auto certification via Let's Encrypt and allow for multiple apps on a single web server.
proxy:
  ssl: true
  host: thomas.justino.fr

# Credentials for your image host.
registry:
  server: ghcr.io
  username: tjustino
  # Always use an access token rather than real password (pulled from .kamal/secrets).
  password:
    - KAMAL_REGISTRY_PASSWORD

# Aliases are triggered with "bin/kamal <alias>". You can overwrite arguments on invocation:
aliases:
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f

# Configure builder setup.
builder:
  arch: amd64

# Use a different ssh user than root
ssh:
  user: app
